import { ProjectCluster, GraphNode, GraphEdge } from "../core/types";

export class ContextGenerator {
  /**
   * Generates a comprehensive CLAUDE.md / AGENTS.md file for a given project cluster
   */
  public static generateClaudeMd(
    project: ProjectCluster,
    nodes: GraphNode[],
    edges: GraphEdge[]
  ): string {
    const activeTech = project.primaryTechStack.join(", ");
    
    // Find rejected nodes related to this project
    const projNodeId = `node_proj_${project.id}`;
    const projectRejections = edges
      .filter(e => e.sourceNodeId === projNodeId && e.relation === "REJECTED")
      .map(e => `- ${e.context}`);

    // Find preferences
    const preferences = nodes
      .filter(n => n.type === "UserPreference")
      .map(n => `- ${n.name}`);

    return `# Project Guidelines: ${project.name}

> Auto-generated by Universal AI Memory from ${project.conversationIds.length} historical conversations.
> Last updated: ${new Date(project.updatedAt).toLocaleDateString()}

## Tech Stack
- **Ecosystem**: ${activeTech || "TypeScript / Modern Web"}

## Key Architectural Decisions
${project.keyDecisions.length > 0 ? project.keyDecisions.map(d => `- ${d}`).join("\n") : "- Follow standard modern modular architecture."}

## Architecture Guardrails & Negative Knowledge (Do NOT Use)
${projectRejections.length > 0 ? projectRejections.join("\n") : "- No explicit anti-patterns recorded yet."}

## Coding Preferences & Conventions
${preferences.length > 0 ? preferences.join("\n") : "- Prefer clean, modular TypeScript with strict type checking."}
- Ensure local secrets and credentials are never hardcoded.
- Maintain minimal external dependencies where possible.
`;
  }

  /**
   * Generates a .cursorrules snippet
   */
  public static generateCursorRules(project: ProjectCluster): string {
    return `You are working on ${project.name}.
Tech Stack: ${project.primaryTechStack.join(", ")}.
Key Project Decisions:
${project.keyDecisions.map(d => `* ${d}`).join("\n")}
Always respect existing design patterns and avoid deprecated libraries.`;
  }
}
